/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: key.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "key.pb-c.h"
void
key__init(Key *message)
{
	static const Key init_value = KEY__INIT;
	*message = init_value;
}
size_t
key__get_packed_size(const Key *message)
{
	assert(message->base.descriptor == &key__descriptor);
	return protobuf_c_message_get_packed_size(
	    (const ProtobufCMessage *)(message));
}
size_t
key__pack(const Key *message, uint8_t *out)
{
	assert(message->base.descriptor == &key__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t
key__pack_to_buffer(const Key *message, ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor == &key__descriptor);
	return protobuf_c_message_pack_to_buffer(
	    (const ProtobufCMessage *)message, buffer);
}
Key *
key__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
{
	return (Key *)protobuf_c_message_unpack(
	    &key__descriptor, allocator, len, data);
}
void
key__free_unpacked(Key *message, ProtobufCAllocator *allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor == &key__descriptor);
	protobuf_c_message_free_unpacked(
	    (ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor key__field_descriptors[3] = {
	{
	    "type", 1, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_INT32,
	    0,					/* quantifier_offset */
	    offsetof(Key, type), NULL, NULL, 0, /* flags */
	    0, NULL, NULL			/* reserved1,reserved2, etc */
	},
	{
	    "curve", 2, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_INT32,
	    0,					 /* quantifier_offset */
	    offsetof(Key, curve), NULL, NULL, 0, /* flags */
	    0, NULL, NULL			 /* reserved1,reserved2, etc */
	},
	{
	    "kbuf", 3, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_INT32,
	    offsetof(Key, n_kbuf), offsetof(Key, kbuf), NULL, NULL,
	    0,		  /* flags */
	    0, NULL, NULL /* reserved1,reserved2, etc */
	},
};
static const unsigned key__field_indices_by_name[] = {
	1, /* field[1] = curve */
	2, /* field[2] = kbuf */
	0, /* field[0] = type */
};
static const ProtobufCIntRange key__number_ranges[1 + 1] = { { 1, 0 },
	{ 0, 3 } };
const ProtobufCMessageDescriptor key__descriptor = {
	PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC, "key", "Key", "Key", "",
	sizeof(Key), 3, key__field_descriptors, key__field_indices_by_name, 1,
	key__number_ranges, (ProtobufCMessageInit)key__init, NULL, NULL,
	NULL /* reserved[123] */
};
