#include <stdlib.h>
#include "sgx_utils.h" //sgx_status_t
#include "sgx_eid.h" //sgx_enclave_id
#include "name_service.h"

extern sgx_enclave_id_t global_eid;

/* This is so don't have to include *_t.h that is generated by edger8r*/
int ecall_add_user(sgx_enclave_id_t eid, int* retval, const char* username, const char* password);
int ecall_auth_user(sgx_enclave_id_t eid, int* retval, const char* username, const char* password);

/*
int ecall_add_user(const char* username, const char* password);
int ecall_auth_user(const char* username, const char* password);
*/

static int add_user(name_service_t *ns, const char *username, const char *password);
static int auth_user(name_service_t *ns, const char *username, const char *password);

name_service_t *init_name_service() {  
  name_service_t *ns = malloc(sizeof(name_service_t));
  //ns->add_user = add_user;
  //ns->auth_user = auth_user;
  return ns;
}

/*
int add_user(name_service_t *ns, const char *username, const char *password) {
  int ret; 
  sgx_status_t status = ecall_add_user(global_eid, &ret, username, password);
  ret = (status) ? 0 : ret;
  return ret;
}

int auth_user(name_service_t *ns, const char *username, const char *password) {
  int ret; 
  sgx_status_t status = ecall_auth_user(global_eid, &ret, username, password);
  ret = (status) ? 0 : ret;
  return ret;

}
*/
