/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: kvcrdt.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "kvcrdt.pb-c.h"
void kvcrdt_pair__init(KvcrdtPair *message) {
  static const KvcrdtPair init_value = KVCRDT_PAIR__INIT;
  *message = init_value;
}
size_t kvcrdt_pair__get_packed_size(const KvcrdtPair *message) {
  assert(message->base.descriptor == &kvcrdt_pair__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t kvcrdt_pair__pack(const KvcrdtPair *message, uint8_t *out) {
  assert(message->base.descriptor == &kvcrdt_pair__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t kvcrdt_pair__pack_to_buffer(const KvcrdtPair *message,
                                   ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &kvcrdt_pair__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
KvcrdtPair *kvcrdt_pair__unpack(ProtobufCAllocator *allocator, size_t len,
                                const uint8_t *data) {
  return (KvcrdtPair *)protobuf_c_message_unpack(&kvcrdt_pair__descriptor,
                                                 allocator, len, data);
}
void kvcrdt_pair__free_unpacked(KvcrdtPair *message,
                                ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor == &kvcrdt_pair__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void kvcrdt_table__init(KvcrdtTable *message) {
  static const KvcrdtTable init_value = KVCRDT_TABLE__INIT;
  *message = init_value;
}
size_t kvcrdt_table__get_packed_size(const KvcrdtTable *message) {
  assert(message->base.descriptor == &kvcrdt_table__descriptor);
  return protobuf_c_message_get_packed_size(
      (const ProtobufCMessage *)(message));
}
size_t kvcrdt_table__pack(const KvcrdtTable *message, uint8_t *out) {
  assert(message->base.descriptor == &kvcrdt_table__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t kvcrdt_table__pack_to_buffer(const KvcrdtTable *message,
                                    ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &kvcrdt_table__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message,
                                           buffer);
}
KvcrdtTable *kvcrdt_table__unpack(ProtobufCAllocator *allocator, size_t len,
                                  const uint8_t *data) {
  return (KvcrdtTable *)protobuf_c_message_unpack(&kvcrdt_table__descriptor,
                                                  allocator, len, data);
}
void kvcrdt_table__free_unpacked(KvcrdtTable *message,
                                 ProtobufCAllocator *allocator) {
  if (!message)
    return;
  assert(message->base.descriptor == &kvcrdt_table__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor kvcrdt_pair__field_descriptors[3] = {
    {
        "key", 1, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_UINT64,
        0,                                        /* quantifier_offset */
        offsetof(KvcrdtPair, key), NULL, NULL, 0, /* flags */
        0, NULL, NULL                             /* reserved1,reserved2, etc */
    },
    {
        "value", 2, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_BYTES,
        0,                                          /* quantifier_offset */
        offsetof(KvcrdtPair, value), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "versions", 3, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_MESSAGE,
        0, /* quantifier_offset */
        offsetof(KvcrdtPair, versions), &version_vector__descriptor, NULL,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
};
static const unsigned kvcrdt_pair__field_indices_by_name[] = {
    0, /* field[0] = key */
    1, /* field[1] = value */
    2, /* field[2] = versions */
};
static const ProtobufCIntRange kvcrdt_pair__number_ranges[1 + 1] = {{1, 0},
                                                                    {0, 3}};
const ProtobufCMessageDescriptor kvcrdt_pair__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "kvcrdt_pair",
    "KvcrdtPair",
    "KvcrdtPair",
    "",
    sizeof(KvcrdtPair),
    3,
    kvcrdt_pair__field_descriptors,
    kvcrdt_pair__field_indices_by_name,
    1,
    kvcrdt_pair__number_ranges,
    (ProtobufCMessageInit)kvcrdt_pair__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor kvcrdt_table__field_descriptors[3] = {
    {
        "uid", 1, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_UINT64,
        0,                                         /* quantifier_offset */
        offsetof(KvcrdtTable, uid), NULL, NULL, 0, /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
    {
        "pairs", 2, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_MESSAGE,
        offsetof(KvcrdtTable, n_pairs), offsetof(KvcrdtTable, pairs),
        &kvcrdt_pair__descriptor, NULL, 0, /* flags */
        0, NULL, NULL                      /* reserved1,reserved2, etc */
    },
    {
        "versions", 3, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_MESSAGE,
        0, /* quantifier_offset */
        offsetof(KvcrdtTable, versions), &version_vector__descriptor, NULL,
        0,            /* flags */
        0, NULL, NULL /* reserved1,reserved2, etc */
    },
};
static const unsigned kvcrdt_table__field_indices_by_name[] = {
    1, /* field[1] = pairs */
    0, /* field[0] = uid */
    2, /* field[2] = versions */
};
static const ProtobufCIntRange kvcrdt_table__number_ranges[1 + 1] = {{1, 0},
                                                                     {0, 3}};
const ProtobufCMessageDescriptor kvcrdt_table__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "kvcrdt_table",
    "KvcrdtTable",
    "KvcrdtTable",
    "",
    sizeof(KvcrdtTable),
    3,
    kvcrdt_table__field_descriptors,
    kvcrdt_table__field_indices_by_name,
    1,
    kvcrdt_table__number_ranges,
    (ProtobufCMessageInit)kvcrdt_table__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
