/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: keycert.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "keycert.pb-c.h"
void   keycert__init
                     (Keycert         *message)
{
  static const Keycert init_value = KEYCERT__INIT;
  *message = init_value;
}
size_t keycert__get_packed_size
                     (const Keycert *message)
{
  assert(message->base.descriptor == &keycert__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t keycert__pack
                     (const Keycert *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &keycert__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t keycert__pack_to_buffer
                     (const Keycert *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &keycert__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Keycert *
       keycert__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Keycert *)
     protobuf_c_message_unpack (&keycert__descriptor,
                                allocator, len, data);
}
void   keycert__free_unpacked
                     (Keycert *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &keycert__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor keycert__field_descriptors[3] =
{
  {
    "key_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Keycert, key_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Keycert, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Keycert, cert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned keycert__field_indices_by_name[] = {
  2,   /* field[2] = cert */
  1,   /* field[1] = key */
  0,   /* field[0] = key_type */
};
static const ProtobufCIntRange keycert__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor keycert__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "keycert",
  "Keycert",
  "Keycert",
  "",
  sizeof(Keycert),
  3,
  keycert__field_descriptors,
  keycert__field_indices_by_name,
  1,  keycert__number_ranges,
  (ProtobufCMessageInit) keycert__init,
  NULL,NULL,NULL    /* reserved[123] */
};
