/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: map.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "map.pb-c.h"
void
strmap_entry_proto__init(StrmapEntryProto *message)
{
	static const StrmapEntryProto init_value = STRMAP_ENTRY_PROTO__INIT;
	*message = init_value;
}
size_t
strmap_entry_proto__get_packed_size(const StrmapEntryProto *message)
{
	assert(message->base.descriptor == &strmap_entry_proto__descriptor);
	return protobuf_c_message_get_packed_size(
	    (const ProtobufCMessage *)(message));
}
size_t
strmap_entry_proto__pack(const StrmapEntryProto *message, uint8_t *out)
{
	assert(message->base.descriptor == &strmap_entry_proto__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t
strmap_entry_proto__pack_to_buffer(
    const StrmapEntryProto *message, ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor == &strmap_entry_proto__descriptor);
	return protobuf_c_message_pack_to_buffer(
	    (const ProtobufCMessage *)message, buffer);
}
StrmapEntryProto *
strmap_entry_proto__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
{
	return (StrmapEntryProto *)protobuf_c_message_unpack(
	    &strmap_entry_proto__descriptor, allocator, len, data);
}
void
strmap_entry_proto__free_unpacked(
    StrmapEntryProto *message, ProtobufCAllocator *allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor == &strmap_entry_proto__descriptor);
	protobuf_c_message_free_unpacked(
	    (ProtobufCMessage *)message, allocator);
}
void
strmap_proto__init(StrmapProto *message)
{
	static const StrmapProto init_value = STRMAP_PROTO__INIT;
	*message = init_value;
}
size_t
strmap_proto__get_packed_size(const StrmapProto *message)
{
	assert(message->base.descriptor == &strmap_proto__descriptor);
	return protobuf_c_message_get_packed_size(
	    (const ProtobufCMessage *)(message));
}
size_t
strmap_proto__pack(const StrmapProto *message, uint8_t *out)
{
	assert(message->base.descriptor == &strmap_proto__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t
strmap_proto__pack_to_buffer(
    const StrmapProto *message, ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor == &strmap_proto__descriptor);
	return protobuf_c_message_pack_to_buffer(
	    (const ProtobufCMessage *)message, buffer);
}
StrmapProto *
strmap_proto__unpack(
    ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
{
	return (StrmapProto *)protobuf_c_message_unpack(
	    &strmap_proto__descriptor, allocator, len, data);
}
void
strmap_proto__free_unpacked(StrmapProto *message, ProtobufCAllocator *allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor == &strmap_proto__descriptor);
	protobuf_c_message_free_unpacked(
	    (ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor
    strmap_entry_proto__field_descriptors[2] = {
	    {
		"first", 1, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_STRING,
		0, /* quantifier_offset */
		offsetof(StrmapEntryProto, first), NULL, NULL, 0, /* flags */
		0, NULL, NULL /* reserved1,reserved2, etc */
	    },
	    {
		"second", 2, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_STRING,
		0, /* quantifier_offset */
		offsetof(StrmapEntryProto, second), NULL, NULL, 0, /* flags */
		0, NULL, NULL /* reserved1,reserved2, etc */
	    },
    };
static const unsigned strmap_entry_proto__field_indices_by_name[] = {
	0, /* field[0] = first */
	1, /* field[1] = second */
};
static const ProtobufCIntRange strmap_entry_proto__number_ranges[1 + 1] = {
	{ 1, 0 }, { 0, 2 }
};
const ProtobufCMessageDescriptor strmap_entry_proto__descriptor = {
	PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC, "strmap_entry_proto",
	"StrmapEntryProto", "StrmapEntryProto", "", sizeof(StrmapEntryProto), 2,
	strmap_entry_proto__field_descriptors,
	strmap_entry_proto__field_indices_by_name, 1,
	strmap_entry_proto__number_ranges,
	(ProtobufCMessageInit)strmap_entry_proto__init, NULL, NULL,
	NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor strmap_proto__field_descriptors[1] = {
	{
	    "entries", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_MESSAGE,
	    offsetof(StrmapProto, n_entries), offsetof(StrmapProto, entries),
	    &strmap_entry_proto__descriptor, NULL, 0, /* flags */
	    0, NULL, NULL /* reserved1,reserved2, etc */
	},
};
static const unsigned strmap_proto__field_indices_by_name[] = {
	0, /* field[0] = entries */
};
static const ProtobufCIntRange strmap_proto__number_ranges[1 + 1] = { { 1, 0 },
	{ 0, 1 } };
const ProtobufCMessageDescriptor strmap_proto__descriptor = {
	PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC, "strmap_proto", "StrmapProto",
	"StrmapProto", "", sizeof(StrmapProto), 1,
	strmap_proto__field_descriptors, strmap_proto__field_indices_by_name, 1,
	strmap_proto__number_ranges, (ProtobufCMessageInit)strmap_proto__init,
	NULL, NULL, NULL /* reserved[123] */
};
