
#ifndef __POLICY_ERRLIST_H__

#define __POLICY_ERRLIST_H__


#define ACTION_SUCCESS 0
#define USER_EXISTS 320
#define USER_NOEXIST 321
#define INCORRECT_PW 322
#define AUTH_FAILED 320
#define INVALID_KEY 319
#define NOEXIST_POLICY 318
#define ACTION_NOPERM_POLICY 317
#define WRONG_UID 316
#endif
