
#ifndef __POLICY_ERRLIST_H__
#define __POLICY_ERRLSIT_H__

#define USER_NOEXIST 321
#define INCORRECT_PW 322
#define AUTH_FAILED 320
#define INVALID_KEY 319
#define NOEXIST_POLICY 318
#define INVALID_ACTION 317

#endif
