/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: store.proto */

#ifndef PROTOBUF_C_store_2eproto__INCLUDED
#define PROTOBUF_C_store_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "vvec.pb-c.h"

typedef struct _Entry Entry;
typedef struct _Table Table;


/* --- enums --- */


/* --- messages --- */

struct  _Entry
{
  ProtobufCMessage base;
  ProtobufCBinaryData key;
  ProtobufCBinaryData value;
  VersionVector *versions;
};
#define ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&entry__descriptor) \
    , {0,NULL}, {0,NULL}, NULL }


struct  _Table
{
  ProtobufCMessage base;
  uint64_t uid;
  size_t n_entries;
  Entry **entries;
  VersionVector *versions;
};
#define TABLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&table__descriptor) \
    , 0, 0,NULL, NULL }


/* Entry methods */
void   entry__init
                     (Entry         *message);
size_t entry__get_packed_size
                     (const Entry   *message);
size_t entry__pack
                     (const Entry   *message,
                      uint8_t             *out);
size_t entry__pack_to_buffer
                     (const Entry   *message,
                      ProtobufCBuffer     *buffer);
Entry *
       entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   entry__free_unpacked
                     (Entry *message,
                      ProtobufCAllocator *allocator);
/* Table methods */
void   table__init
                     (Table         *message);
size_t table__get_packed_size
                     (const Table   *message);
size_t table__pack
                     (const Table   *message,
                      uint8_t             *out);
size_t table__pack_to_buffer
                     (const Table   *message,
                      ProtobufCBuffer     *buffer);
Table *
       table__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   table__free_unpacked
                     (Table *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Entry_Closure)
                 (const Entry *message,
                  void *closure_data);
typedef void (*Table_Closure)
                 (const Table *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor entry__descriptor;
extern const ProtobufCMessageDescriptor table__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_store_2eproto__INCLUDED */
